### ISSUE TITLE
forget to add root namespace in Module on line 123

### ISSUE THREAD

**Issue by abos5** [digiaonline/yii-account#6]
As Yii::import import class according to rootAlias only, using configs,

<pre>
aliases 
     '\nordsoftware\yii_account' => realpath(__DIR__ . '/../../vendor/nordsoftware/yii-account/src'),
component  web
    'class' => '\nordsoftware\yii_account\components\WebUser',
</pre> 

is not working until I changed setting to 

<pre>
aliases 
   'nordsoftware' => realpath(__DIR__ . '/../../vendor/nordsoftware'),
component  web
    'class' => '\nordsoftware\yii_account\components\WebUser',
--
besides, directory "nordsoftware/yii-account/src"  was moved to "nordsoftware/yii_account"
</pre> 

Is it an issue or is something wrong with my setting?

**Comment by hugovk** [comment]
Closing and archiving repo.
